### PR TITLE
Some restructuring

### PR DESCRIPTION
**Pull request by Dryvnt**
I fixed up the GetDayofWeek function to use _math_ to solve the problem. This reduced the file size greatly.

I also changed a bit on global variables, making the code less verbose. I removed the `year`, `week`, `day` global variables, since they were only used to set the `displayYear`, etc. variables.

And whitespace. Because autoformatting. I am sorry.

### CODE REVIEW

**Comment by TheOneReed** [comment]
I'm going to have to research what is going on there. That is some magic for sure.

**Review by TheOneReed — CHANGES_REQUESTED** [review]
Doesn't work. Returns incorrect day. Function returns Wednesday(4) for the 18th Nov 2016, should be Friday(6).

**Comment by Dryvnt** [comment]
What the heck. 18th Nov 2016 returns 6 for me. Are you sure you tested it right? >.<

**Comment by TheOneReed** [comment]
Okay, think I found it. On the wiki the formula is (y + y/4 - y/100 + y/400 + t[m-1] + d) % 7; You have + y/100. Unintentional sign flip?

Edit: So got home, and tested it in the Calendar itself, and your original code works. I have no idea how. When I used the Wiki Function outside of the program, it works, and yours doesn't. But inside it does, and I have no idea why.

**Pull request merged**
